# ----
# Site

title: Salsah documentation
url: https://dhlab-basel.github.io/Salsah
version: v2.1.2
baseurl:
google_analytics_key:
show_full_navigation: true
template: https://code.getmdl.io/1.3.0/material.teal-amber.min.css
git:
  name: Github
  repository: Salsah
  url: https://github.com/dhlab-basel/Salsah

company:
  company_name: Data and Service Center for the Humanities DaSCH
  mission_statement: The main task of the Data and Service Center for Humanities (DaSCH) is to operate a platform for humanities research data. In addition, the networking of data with other databases is to be promoted (linked open data).
  address: Bernoullistrasse 32, 4056 Basel
  phone: +41 (0)61 207 04 89
  email: info@knora.org
  twitter: dhlabbasel
  github: dhlab-basel


links:
  company: <a href="http://dasch.swiss">Data and Service Center for the Humanities</a>
  knora: <a href="https://knora.org">Knora</a>
  knora-docs: <a href="https://docs.knora.org">Documentation</a>
  knora-ui: <a href="https://npmjs.com/~knora">Knora-ui modules</a>
  sipi: <a href="https://sipi.io">Sipi</a>
  salsah: <a href="https://dhlab-basel.github.io/Salsah">Salsah</a>
  dhlab: <a href="http://dhlab.unibas.ch">Digital Humanities Lab</a>
  dasch: <a href="http://dasch.swiss">Data and Service Center for the Humanities DaSCH</a>
  unibas: <a href="http://unibas.ch">University of Basel</a>


# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: assets/images/touch-icon.png
description: Salsah is the generic user interface (front-end) for <a href="https://knora.org">Knora</a> (back-end) &mdash; a software framework for storing, sharing, and working with primary sources and data in the humanities. Both application supports <a href="https://sipi.io">Sipi</a> a iiif media service.
author:
  name: DHLab and DaSCH
  email: info@knora.org

# -----
# Build

timezone: Etc/UTC

permalink: pretty

collections:
  docs:
    output: true
    permalink: docs/:path/
  manual:
    output: true
    permalink: manual/:path/
  features:
    output: true
    permalink: features/:name

defaults:
-
  scope:
    path: ""
  values:
    layout: "default"
-
  scope:
    path: ""
    type: "docs"
  values:
    layout: post
    seo:
      type: Article
-
  scope:
    path: ""
    type: "manual"
  values:
    layout: post
    seo:
      type: Article
-
  scope:
    path: ""
    type: "releasenotes"
  values:
    _comments:
        type: Marks the impact of this release


plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed

exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENCE
