# ----
# Site

title: Salsah Documentation
url: https://dhlab-basel.github.io/Salsah
version: v2.0.0-alpha.13
baseurl:
google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /assets/images/salsah-logo-white.png
description: System for Annotation and Linkage of Sources in Arts and Humanities (Salsah) — the generic user interface for Knora
author:
  name: Digital Humanities Lab, University of Basel
  url: http://dhlab.unibas.ch
  email: info@knora.org
  twitter: DHLabBasel
git:
  name: github
  title: GitHub
  url: https://github.com/dhlab-basel/Salsah

# -----
# Build

timezone: Europe/Zurich

markdown: kramdown
permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "releasenotes"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
